#!/usr/bin/env php
<?php

use \Doctrine\DBAL\Migrations\Tools\Console\Command;


set_time_limit(0);

$app = require_once __DIR__ . '/bootstrap.php';

$app->register(new \Knp\Provider\MigrationServiceProvider(), array(
    'migration.path' => __DIR__ . '/migrations'
));

$app['console']->add(new \SilexStarter\Command\SomeCommand());

$app['console']->run();