#!/usr/bin/env php
<?php

set_time_limit(0);

use \SilexStarter\Provider\MigrationServiceProvider;
use SilexStarter\Command\SomeCommand;

$app = require_once __DIR__ . '/bootstrap.php';

$app->register(new MigrationServiceProvider());

$app['console']->add(new SomeCommand());

$app['console']->run();